FROM docker.io/python:3.8

RUN : \
    && apt-get update \
    && apt-get install -y libpq-dev python3.8-dev \
    && apt-get clean \
    && rm -fr /var/lib/apt/lists/*

# Project
WORKDIR /app
COPY ./app ./app
COPY ./app/tests ./app/tests
COPY ./requirements ./requirements

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install -r /app/requirements/local.txt
