"""empty message

Revision ID: ac79eda1c94f
Revises: 
Create Date: 2023-08-23 18:23:47.156468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac79eda1c94f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id_course', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.Text(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ic_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('results',
    sa.Column('id_result', sa.Integer(), nullable=False),
    sa.Column('cd_student', sa.Integer(), nullable=False),
    sa.Column('cd_course', sa.Integer(), nullable=False),
    sa.Column('score', sa.Text(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ic_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_result')
    )
    op.create_table('students',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('family_name', sa.Text(), nullable=False),
    sa.Column('date_birth', sa.DateTime(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ic_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('st_firstname', sa.Text(), nullable=False),
    sa.Column('st_lastname', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('em_user_email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ic_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('em_user_email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('results')
    op.drop_table('courses')
    # ### end Alembic commands ###
